user:
  username: zhangsan@prod
  age: 20
  lists: [cat,dog,pig]
  maps: {k1: v1,k2: 12}

developer:
  name: kongxiao@prod
  phone-number: xxxxxx@prod

blog:
  name: Spring Boot
  title: 配置文件
  desc: ${blog.name}的标题是${blog.title}